name: Run tests

on:
  push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Create new user
        uses: actions/requests@v3

      - name: setap Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: istall requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest


